apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: LoadBalancer
  selector:
    component: web #provide acces to client pod
  ports:
    - port: 80
      targetPort: 80